### ISSUE TITLE
Estado actual del proyecto? 

### ISSUE THREAD

**Issue by Bonabrux** [hjf/esphome-x28#2]
Hola como estas?
Tenía un poco de fe que con la llegada del wificom100 X28 se pondría las pilas habilitando un acceso API, pero ayer me respondieron un correo (de forma muy poca amistosa, clásica del SAT X28) diciendo que no lo harán.
Por lo cual, buscando otros horizontes llegue a tu proyecto. Esta Genial!
Quería saber cual es el status actual del mismo? Y como haz hecho con ESP32 para usarlo de Sniffer y así descubrir los códigos?

Tengo poca/nada experiencia con ESP32, pero si con Arduino y programación C++, etc. Por lo cual no creo tener muchos problemas para adaptarme. 

Mi intención es poder integrar a HomeAssistant tambien:
* Verificación de estado de sensores (Puerta/Movimiento)
* Verificación de estado de Nodos (Nodo activo/inactivo)
* Comando de nodos (ej: encender luces mediante HA, ps: tengo varios clientes con control de luces a través de X28 con MCA y MagicTouch)

Aguardo tus comentarios,
Gracias

**Comment by hjf** [comment]
Hola. El proyecto funciona, de hecho el otro dia vi un tipo por mi terraza y pude apretar el boton de panico en el HA en el celular e hice sonar la alarma.

Este proyecto esta basado en este: https://github.com/gbisheimer/x28_sniffer que es para arduino. Con ese podes escanear todos los códigos de la alarma porque los va tirando a la consola. Yo solo saque los que pude.

El proyecto en ESP32, asi como esta, lo cargas en un ESP32 con ESPHome y sale andando. Sin conectarlo a HA con la consola serial ya podes ir sniffeando el protocolo. Imprime a la consola cada mensaje MPX que va pasando, y aquellos que reconoce los notifica a HA.

Lo que deberias hacer es armar el circuito, programarlo con ESPHome, y luego ir haciendo cosas con la alarma. Vas a ver un monton de trafico. Cada sensor que cambia manda uno o mas paquetes. Lo mismo con los botones  etc. Cuando tengas mas codigos vas cambiando el x28.h y el yaml para agregar nuevas funcionalidades

**Comment by Bonabrux** [comment]
Genial, muchas gracias por tu respuesta.
Esta semana me llegará el esp32 para comenzar las pruebas. Y ya tengo un sistema completo en MPXH sobre la mesa de pruebas. Mi intención es obtener/entender la mayor cantidad de comandos posibles (principalmente en lo que a Domotica refiere estado de alarma, estado de sensores, control de nodos, etc). Voy a reportar aquí una vez que tenga una lista interesante.

Saludos
